countryCode="BD"
authorization="SAPISIDHASH 1710931802_506efe53652f00359f0867f85be1aef82aa59484"
x-goog-authuser=1

[[playlists]]
name="music"
id="PLAsIFGKl2toYRLAfKyhaytE29s5nxDjAY"

[[playlists]]
name="anime"
id="PLAsIFGKl2toYzt-cN5KMzqV9-C56hldWv"

[[playlists]]
name="general"
id="PLAsIFGKl2toZU6o_wNIP8SAbA4z7yMn16"

[[playlists]]
name="later"
id="PLAsIFGKl2toZc3xeHkHuv71JBk8oQW5Nt"