context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Music EQ"
            media.name       = "Music EQ"
            filter.graph = {
                nodes = [
                    {
                        type    = builtin
                        name    = band0
                        label   = bq_peaking
                        control = { "Freq" = 31.0 "Q" = 0.707 "Gain" = -8.0 }
                    }
                    {
                        type    = builtin
                        name    = band1
                        label   = bq_peaking
                        control = { "Freq" = 62.0 "Q" = 0.707 "Gain" = -12.0 }
                    }
                    {
                        type    = builtin
                        name    = band2
                        label   = bq_peaking
                        control = { "Freq" = 125.0 "Q" = 0.707 "Gain" = -15.0 }
                    }
                    {
                        type    = builtin
                        name    = band3
                        label   = bq_peaking
                        control = { "Freq" = 250.0 "Q" = 1.414 "Gain" = 3.0 }
                    }
                    {
                        type    = builtin
                        name    = band4
                        label   = bq_peaking
                        control = { "Freq" = 500.0 "Q" = 1.414 "Gain" = 7.0 }
                    }
                    {
                        type    = builtin
                        name    = band5
                        label   = bq_peaking
                        control = { "Freq" = 1000.0 "Q" = 1.414 "Gain" = 5 }
                    }
                    {
                        type    = builtin
                        name    = band6
                        label   = bq_peaking
                        control = { "Freq" = 2000.0 "Q" = 1.414 "Gain" = 0.0 }
                    }
                    {
                        type    = builtin
                        name    = band7
                        label   = bq_peaking
                        control = { "Freq" = 4000.0 "Q" = 1.414 "Gain" = 0.0 }
                    }
                    {
                        type    = builtin
                        name    = band8
                        label   = bq_peaking
                        control = { "Freq" = 8000.0 "Q" = 1.414 "Gain" = 0.0 }
                    }
                    {
                        type    = builtin
                        name    = band9
                        label   = bq_peaking
                        control = { "Freq" = 16000.0 "Q" = 1.414 "Gain" = 0.0 }
                    }
                ]
                links = [
                    { output = "band0:Out" input = "band1:In" }
                    { output = "band1:Out" input = "band2:In" }
                    { output = "band2:Out" input = "band3:In" }
                    { output = "band3:Out" input = "band4:In" }
                    { output = "band4:Out" input = "band5:In" }
                    { output = "band5:Out" input = "band6:In" }
                    { output = "band6:Out" input = "band7:In" }
                    { output = "band7:Out" input = "band8:In" }
                    { output = "band8:Out" input = "band9:In" }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "effect_input.music_eq"
                media.class = Audio/Sink
                filter.smart = true
            }
            playback.props = {
                node.name   = "effect_output.music_eq"
                node.passive = true
            }
        }
    }
]
