#!/bin/bash

red='\033[31m'
colorOff='\033[0m'
cancel() { echo -e "$red$1$colorOff"; exit 1; }

efiDisk="/dev/nvme0n1"
efiPart="1"
osDisk="/dev/nvme0n1p2"
label="Arch Linux"

osUuid=$(blkid -s UUID -o value $osDisk) || cancel "failed to get UUID for $osDisk"

if ! efibootmgr | grep -q "\* $label"; then
    efibootmgr --create --disk $efiDisk --part $efiPart --label "$label" \
        --loader /vmlinuz-linux \
        --unicode "root=UUID=$osUuid rw zswap.enabled=0 initrd=\\amd-ucode.img initrd=\\booster-linux.img"
fi
