#!/bin/bash

red='\033[31m'
colorOff='\033[0m'
cancel() { echo -e "$red$1$colorOff"; exit 1; }

efiDisk="/dev/sda"
efiPart="1"
osDisk="/dev/sda2"
label="Arch Linux"

osUuid=$(blkid -s UUID -o value $osDisk) || cancel "failed to get UUID for $osDisk"

baseParams="root=UUID=$osUuid rw initrd=\\amd-ucode.img initrd=\\booster-linux.img"

if ! efibootmgr | grep -qF "* $label"; then
    # processor.max_cstate fixes soft lock freezing on Ryzen: https://wiki.archlinux.org/title/Ryzen#Troubleshooting
    efibootmgr --create --disk $efiDisk --part $efiPart --label "$label" \
        --loader /vmlinuz-linux \
        --unicode "$baseParams"
fi
